### ISSUE TITLE
using js function context

### ISSUE THREAD

**Issue by sagittaracc** [BhavyaBibi/Photo-App#1]
https://github.com/BhavyaBibi/Photo-App/blob/3c3b697cae46377146363951176fc51320635eee/staticfiles/admin/js/SelectBox.js#L7

You can use ```this``` in this context like this:
```js
this.cache[id] = [];
```
when the ```init``` function is called from the context ```SelectBox```

**Comment by BhavyaBibi** [comment]
thanks
